adapters:
  - http
  - ws
debug: true
enableVerify: true
verifyKey: password
singleMode: false
cacheSize: 4096
adapterSettings:
  ## 详情看 http adapter 使用说明 配置
  http:
    host: 127.0.0.1
    port: 8080
    cors: ["*"]
  ws:
    host: 127.0.0.1
    port: 8080
    reservedSyncId: -1